---
title: "AFSC Gulf of Alaska"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{AFSC Gulf of Alaska}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r eval = TRUE}
# Set directories --------------------------------------------------------------
library(here)

wd <- paste0(here::here(), "/vignettes/")
dir_out <- paste0(wd, "output/")
dir_final <- paste0(dir_out, "GOA_0results/")
```


```{r eval = FALSE}
# get rid of memory limits
options(future.globals.maxSize = 1 * 1024^4) # Allow up to 1 TB for globals

# Install Libraries ------------------------------------------------------------

# Here we list all the packages we will need for this whole process
# We'll also use this in our works cited page.
PKG <- c(
  "surveyresamplr",

  # tidyverse
  "dplyr",
  "tidyr",
  "viridis",
  "ggplot2",
  "tibble",
  "janitor",
  "data.table",
  "flextable",

  # parallelizing
  "forcats",
  "purrr",
  "furrr",
  "doParallel",

  # sampling
  "sampling",

  # modeling
  "arrow",
  "future.apply",
  "future.callr",
  "sdmTMB", # install.packages("remotes"",; remotes::install_github("pbs-assess/sdmTMBextra", dependencies = TRUE",
  "Matrix",
  "MASS",
  "cluster",
  "TMB",
  "INLA"
)

pkg_install <- function(p) {
  if (!require(p, character.only = TRUE)) {
    install.packages(p)
  }
  require(p, character.only = TRUE)
}
base::lapply(unique(PKG), pkg_install)

### Define study species -------------------------------------------------------

spp_list <- data.frame(
  srvy = "GOA",
  common_name = c(
    "walleye pollock", "Pacific cod",
    "Pacific ocean perch", "flathead sole",
    "northern rockfish", "arrowtooth flounder"
  ),
  species_code = as.character(c(
    21740, 21720,
    30060, 10130,
    30420, 10110
  )),
  filter_lat_lt = NA,
  filter_lat_gt = NA,
  filter_depth = NA,
  model_fn = "total_catch_wt_kg ~ 0 + factor(year)",
  model_family = "delta_gamma",
  model_anisotropy = TRUE,
  model_spatiotemporal = "iid, iid"
) |>
  dplyr::mutate(
    file_name = gsub(pattern = " ", replacement = "_", x = (tolower(common_name)))
  )

### Load survey data -----------------------------------------------------------

# source(paste0(wd, "code/data_dl_ak.r"))
catch <- surveyresamplr::noaa_afsc_catch |>
  dplyr::filter(srvy == "GOA")

### Load grid data -------------------------------------------------------------

grid_yrs <- replicate_df(surveyresamplr::noaa_afsc_goa_pred_grid_depth, "year", unique(catch$year))

### Variables ------------------------------------------------------------------

srvy <- "GOA"
seq_from <- 0.2
seq_to <- 1.0
seq_by <- 0.2
tot_dataframes <- 13
replicate_num <- 3

### Run ------------------------------------------------------------------------

sink(file = paste0(dir_out, srvy, "_", Sys.Date(), "_logfile.txt"), append = FALSE, split = TRUE) # for screen and log
map(
  1:nrow(spp_list),
  ~ clean_and_resample(spp_list[.x, ],
    catch, seq_from, seq_to, seq_by,
    tot_dataframes, replicate_num, grid_yrs, dir_out,
    test = TRUE
  )
)
sink()

### Plot indices --------------------------------------------------------------

out <- plot_results(srvy = srvy, dir_out = dir_out, dir_final = dir_final)
```

```{r results-run, eval = TRUE, echo = FALSE}
load(file = paste0(dir_final, "analysisoutput.rdata"))
```

```{r results-plots}
out$plots
```

Parameter output: 

```{r results-tables-1}
i <- 1
print(names(out$tables)[i])
head(out$tables[i][[1]]) |>
  flextable::flextable()
```


```{r results-tables-2}
i <- 1 + i
print(names(out$tables)[i])
head(out$tables[i][[1]]) |>
  flextable::flextable()
```


```{r results-tables-3}
i <- 1 + i
print(names(out$tables)[i])
head(out$tables[i][[1]]) |>
  flextable::flextable()
```


```{r results-tables-4}
i <- 1 + i
print(names(out$tables)[i])
head(out$tables[i][[1]]) |>
  flextable::flextable()
```
