---
title: "A Simple Example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{simple-example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(surveyresamplr)
```


```{r eval = FALSE}
#get rid of memory limits
options(future.globals.maxSize = 1 * 1024^4)  # Allow up to 1 TB for globals

# Set directories --------------------------------------------------------------
library(here)

wd <- paste0(here::here(),"/vignettes/")
dir_out <- paste0(wd, "output/")
crs_latlon <- "+proj=longlat +datum=WGS84" # decimal degrees

# Install Libraries ------------------------------------------------------------

# Here we list all the packages we will need for this whole process
# We'll also use this in our works cited page. 
PKG <- c(
  "surveyresamplr",

  # tidyverse
  "dplyr",
  "magrittr",
  "tidyr",
  "viridis",
  "ggplot2", 
  "tibble",
  "janitor", 
  "data.table", 
  
  # parallelizing
  "forcats",
  "purrr",
  "furrr", 
  "doParallel",
  
  # sampling
  "sampling",
  
  # modeling
  "arrow", 
  "future.apply", 
  "future.callr", 
  "sdmTMB", # install.packages("remotes"",; remotes::install_github("pbs-assess/sdmTMBextra", dependencies = TRUE",
  "Matrix", 
  "MASS",
  "cluster", 
  "TMB", 
  "INLA" 
)

# Use pkg_install() function found in functions.R file to load packages
source("./inst/r/pkg_install.R")
base::lapply(unique(PKG), pkg_install)

# Run scenarios ----------------------------------------------------------------

## Aleutian Islands ------------------------------------------------------------

### Define study species -------------------------------------------------------

spp_list <- data.frame(
  srvy = "AI",
  common_name = c("walleye pollock", "Pacific cod", 
                  "Pacific ocean perch", "flathead sole", 
                  "northern rockfish", "arrowtooth flounder"), 
  species_code = as.character(c(21740, 21720, 
                                30060, 10130, 
                                30420, 10110)), 
  filter_lat_lt = NA, 
  filter_lat_gt = NA, 
  filter_depth = NA, 
  model_fn = "total_catch_wt_kg ~ 0 + factor(year)",
  model_family = "delta_gamma",
  model_anisotropy = TRUE,
  model_spatiotemporal = c(c("iid, iid"))
) %>% 
  dplyr::mutate( 
    file_name = gsub(pattern = " ", replacement = "_", x = (tolower(common_name)))  )

### Define study species -------------------------------------------------------

spp_list <- data.frame(
  srvy = "CA",
  common_name = c("arrowtooth flounder"),
  file_name = c("arrowtooth_flounder"),
  filter_lat_gt = c(34),
  filter_lat_lt = c(NA),
  filter_depth = c(NA),
  model_fn = c(
    "total_catch_wt_kg ~ 0 + factor(year) + pass"),
  model_family = c("delta_gamma"),
  model_anisotropy = c(TRUE),
  model_spatiotemporal = c(c("iid, iid"))
  )

### Load survey data -----------------------------------------------------------

# source(paste0(wd, "code/data_dl_nw.r"))

catch_ca <- utils::read.csv(paste0(wd,"data/nwfsc_bt_fmp_spp_updated.csv")) #pulled data again to get 2024
catch <- catch_ca %>% 
  dplyr::select(trawlid = Trawl_id, 
                common_name = Common_name, 
                longitude_dd = Longitude_dd, 
                latitude_dd = Latitude_dd, 
                year = Year, 
                pass = Pass, 
                total_catch_wt_kg, 
                depth_m = Depth_m) %>% 
  dplyr::mutate(srvy = "CA")

### Load grid data -------------------------------------------------------------

load(paste0(wd,"grids/noaa_nwfsc_ca_pred_grid_depth.rda"), verbose = TRUE)
pred_grid <- california_current_grid %>% # rename x and y cols
  dplyr::select(longitude_dd = longitude, 
                latitude_dd = latitude, 
                pass = pass_scaled, 
                depth_m = depth, 
                area_km2 = area_km2_WCGBTS) %>% 
  dplyr::mutate(srvy = "CA")
grid_yrs <- replicate_df(pred_grid, "year", unique(catch$year))

### Variables ------------------------------------------------------------------

srvy <- "CA"
seq_from = 0.1
seq_to = 1
seq_by = 0.1
tot_dataframes = 91
replicate_num <- 10

### Run ------------------------------------------------------------------------

sink(file = paste0(dir_out, srvy, "_", Sys.Date(), "_logfile.txt"), append=FALSE, split=TRUE)  # for screen and log
map(
  1:nrow(spp_list), 
  ~ clean_and_resample(spp_list[.x,], 
                       catch, seq_from, seq_to, seq_by, 
                       tot_dataframes, replicate_num, grid_yrs, dir_out))
sink()

### Plot indices ---------------------------------------------------------------

plot_results(srvy = srvy, dir_out = dir_out) 
```
